### ISSUE TITLE
求教，多线程调用Flask服务的时候，怎么创建onnxruntime的session？

### ISSUE THREAD

**Issue by nistarlwc** [leechehao/flask-onnx-ner#1]
看到代码里中文，就直接说了

``` python
import onnxruntime as rt
from flask import Flask, request
app = Flask(__name__)

sess = rt.InferenceSession(model_XXX, providers=['CUDAExecutionProvider'])

@app.route('/algorithm', methods=['POST'])
def parser():
    prediction = sess.run(...)

if __name__ == '__main__':
    app.run(host='127.0.0.1', port='12345', threaded=True)
```
启动了这样的一个flask服务，由于调用端是动态并发的，如果并发多了会造成显存爆满。
尝试了用```intra_op_num_threads = 2```、 ```inter_op_num_threads = 2```、 ```os.environ["OMP_NUM_THREADS"] = "2"```之类的限制onnxruntime的线程数，但是不成功。  
设置最大显存```'gpu_mem_limit'```也失败了。

不明白是为什么？难道是flask在每次被调用的时候，都使用的不同的session？怎么解决呢？

**Comment by leechehao** [comment]
GPU記憶體爆滿的問題是發生在POST的時候，還是剛起服務的時候?

**Comment by nistarlwc** [comment]
Post的时候，单模型会占2G的显存，可以并行跑三个，但是跑第四个就随机卡死一个。

flask要想并发的话，应该是多线程还是多进程？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月26日 13:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [leechehao/flask-onnx-ner] 求教，多线程调用Flask服务的时候，怎么创建onnxruntime的session？ (Issue #1) |

GPU記憶體爆滿的問題是發生在POST的時候，還是剛起服務的時候?

**Comment by leechehao** [comment]
並行跑三個是同時發POST嗎?
應該看你的硬體資源，如果使用多進程需要耗費較大資源，相對多線程較小。

**Comment by nistarlwc** [comment]
我查到了是由于flask存在线程隔离机制导致的。  
每次post的时候，相当于重新复制了一份onnx的session。
现在就是想办法怎么来解决了，你知道吗？




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月26日 16:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [leechehao/flask-onnx-ner] 求教，多线程调用Flask服务的时候，怎么创建onnxruntime的session？ (Issue #1) |

並行跑三個是同時發POST嗎?
應該看你的硬體資源，如果使用多進程需要耗費較大資源，相對多線程較小。
